# 1. netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://script.google.com; img-src 'self' data: https://api.netlify.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;"

# 2. .env.production
VITE_SHEETS_SCRIPT_URL=https://script.google.com/macros/s/AKfycbwn5kOrvRRBvx-7ZhyGj8Bo9XfIQAdHbOsHxuMkHBBx9nRVy6FHEgvflc6IplbSGWl1PA/exec

# 3. package.json
{
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }
}